/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Calisto' at '10/7/16 10:36 AM' with Gradle 2.10
 *
 * @author Calisto, @date 10/7/16 10:36 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
